### ISSUE TITLE
Feature Request: Install on a ZFS partition (in order to allow dual boot)

### ISSUE THREAD

**Issue by allentiak** [ghostbsd/install-station#4]

**Comment by ericbsd** [comment]
That is already supported

**Comment by allentiak** [comment]
Great! I didn't know.

Since which version?

**Comment by ericbsd** [comment]
Not sure wish one it was introduced, but it was on 20.08.04 for sure.

**Comment by allentiak** [comment]
Thanks! Great to know this.
